"""Baseline schema

Revision ID: ae44a6df6a38
Revises: 
Create Date: 2026-08-19 19:35:04.589794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae44a6df6a38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view_all_time_share_positions',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('position_date', sa.Date(), nullable=False),
    sa.Column('share_change', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('storage_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('account_id', 'stock_id', 'position_date')
    )
    op.create_table('view_user_stock_holdings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=False),
    sa.Column('profile_country', sa.String(length=50), nullable=False),
    sa.Column('account_type', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('broker_name', sa.String(length=255), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('native_currency', sa.String(length=3), nullable=False),
    sa.Column('annualized_dividend_per_share', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('total_shares', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('profile_id', 'account_id', 'stock_id')
    )
    op.create_table('health_metric_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('logged_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precious_metal_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metal_type', sa.String(length=50), nullable=False),
    sa.Column('form', sa.String(length=100), nullable=False),
    sa.Column('weight_oz', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('purity_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('purchase_price_per_oz', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_spot_price_per_oz', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('storage_location', sa.String(length=255), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('real_estate_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('property_name', sa.String(length=255), nullable=False),
    sa.Column('property_type', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('property_category', sa.String(length=100), nullable=False),
    sa.Column('structural_type', sa.String(length=100), nullable=False),
    sa.Column('tenure_model', sa.String(length=100), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('mortgage_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_rent_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_expenses', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('is_primary_residence', sa.Boolean(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('washrooms', sa.Integer(), nullable=False),
    sa.Column('garages', sa.Integer(), nullable=False),
    sa.Column('size_sqft', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('real_estate_projections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('real_estate_id', sa.UUID(), nullable=False),
    sa.Column('projection_year', sa.Integer(), nullable=False),
    sa.Column('projected_value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['real_estate_id'], ['real_estate_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dividend_received',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount_per_share', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('shares_at_payment', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('total_received', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['brokerage_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_id'], ['stock_registry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_stock_prices_composite'), table_name='daily_stock_prices')
    op.add_column('investment_profiles', sa.Column('country', sa.String(length=50), nullable=False))
    op.add_column('investment_profiles', sa.Column('account_type', sa.String(length=100), nullable=False))
    op.add_column('investment_profiles', sa.Column('pillar_category', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('primary_country', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('primary_currency', sa.String(length=3), nullable=False))
    op.alter_column('users', 'active_modules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text('\'["STOCKS"]\'::jsonb'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active_modules',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text('\'["STOCKS"]\'::jsonb'))
    op.drop_column('users', 'primary_currency')
    op.drop_column('users', 'primary_country')
    op.drop_column('investment_profiles', 'pillar_category')
    op.drop_column('investment_profiles', 'account_type')
    op.drop_column('investment_profiles', 'country')
    op.create_index(op.f('idx_stock_prices_composite'), 'daily_stock_prices', ['stock_id', sa.literal_column('trading_date DESC')], unique=False)
    op.drop_table('dividend_received')
    op.drop_table('real_estate_projections')
    op.drop_table('real_estate_assets')
    op.drop_table('precious_metal_assets')
    op.drop_table('health_metric_logs')
    op.drop_table('view_user_stock_holdings')
    op.drop_table('view_all_time_share_positions')
    # ### end Alembic commands ###
